use serde_json::{Map, Value};

pub fn statusline_model_contract(api: &str, input: &Value) -> Value {
    match api {
        "compactSessionTitle" => Value::String(compact_session_title(&input["session"])),
        "projectStatuslineMetadata" => project_statusline_metadata(input),
        "renderSemanticBadge" => {
            render_semantic_badge(input.get("semantic").unwrap_or(&Value::Null))
        }
        "renderDashboardScreens" => render_dashboard_screens(string_field(input, "activeScreen")),
        "trim" => Value::String(trim_text(
            string_field(input, "text").unwrap_or(""),
            integer_field(input, "max") as usize,
        )),
        "normalizePath" => Value::String(normalize_path(
            string_field(input, "path"),
            string_field(input, "projectRoot").unwrap_or(""),
        )),
        "resolveCurrentSessionId" => optional_string(resolve_current_session_id(input)),
        "resolveExactCurrentSessionId" => optional_string(resolve_exact_current_session_id(input)),
        "resolveScopedSessions" => Value::Array(resolve_scoped_sessions(input)),
        "resolveFocusedOverseer" => resolve_focused_control(input, "overseer"),
        "resolveFocusedTeammateGroup" => Value::Array(resolve_focused_teammate_group(input)),
        "resolveCurrentTeammates" => Value::Array(resolve_current_teammates(input)),
        "resolveSessionMetadata" => resolve_session_metadata(input, false),
        _ => Value::Null,
    }
}

fn compact_session_title(session: &Value) -> String {
    if string_field(session, "kind") == Some("service")
        && let Some(command) =
            string_field(session, "launchCommandLine").filter(|value| !value.trim().is_empty())
    {
        return command.trim().to_owned();
    }
    let tool = string_field(session, "tool").unwrap_or("");
    let label = string_field(session, "label").unwrap_or("");
    let base = if string_field(session, "kind") == Some("service") {
        if label.trim().is_empty() {
            if tool.is_empty() { "service" } else { tool }
        } else {
            label.trim()
        }
    } else if !is_autogenerated_label(tool, label) && !label.trim().is_empty() {
        label.trim()
    } else if !tool.is_empty() {
        tool
    } else {
        string_field(session, "id").unwrap_or("")
    };
    if string_field(session, "kind") == Some("service") {
        format!("{base}[svc]")
    } else if let Some(role) = string_field(session, "role") {
        format!("{base}({role})")
    } else {
        base.to_owned()
    }
}

fn is_autogenerated_label(tool: &str, label: &str) -> bool {
    let tool = tool.trim().to_ascii_lowercase();
    let label = label.trim().to_ascii_lowercase();
    !tool.is_empty()
        && !label.is_empty()
        && (label == tool || label.starts_with(&format!("{tool}-")))
}

fn project_statusline_metadata(input: &Value) -> Value {
    let mut known = Vec::new();
    for group in input
        .get("groups")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
    {
        for entry in group.as_array().into_iter().flatten() {
            if let Some(id) = string_field(entry, "id") {
                known.push(id.to_owned());
            }
        }
    }
    let mut output = Map::new();
    if let Some(metadata) = input.get("metadata").and_then(Value::as_object) {
        for id in known {
            if let Some(value) = metadata.get(&id) {
                output.insert(id, value.clone());
            }
        }
    }
    Value::Object(output)
}

fn render_semantic_badge(semantic: &Value) -> Value {
    let attention = semantic
        .get("user")
        .and_then(|user| string_field(user, "attention"));
    let label = semantic
        .get("user")
        .and_then(|user| string_field(user, "label"));
    let badge = match (attention, label) {
        (Some("error"), _) => Some("✗"),
        (Some("needs_input" | "needs_response"), _) => Some("?"),
        (Some("blocked"), _) => Some("!"),
        (_, Some("done")) => Some("✓"),
        (_, Some("working")) => Some("↻"),
        (_, Some("starting")) => Some("…"),
        _ => None,
    };
    badge
        .map(|badge| Value::String(badge.to_owned()))
        .unwrap_or(Value::Null)
}

fn render_dashboard_screens(active_screen: Option<&str>) -> Value {
    let active = active_screen.unwrap_or("dashboard");
    let tabs = [
        ("dashboard", "Dashboard", "d"),
        ("coordination", "Coordination", "c"),
        ("project", "Project", "p"),
        ("library", "Library", "l"),
        ("topology", "Topology", "t"),
        ("graveyard", "Graveyard", "g"),
    ];
    Value::Array(
        tabs.iter()
            .map(|(key, label, hotkey)| {
                if *key == active {
                    return Value::String(format!("#[fg=black,bg=yellow] {label} #[default]"));
                }
                let lower = label.to_ascii_lowercase();
                let index = lower.find(hotkey).unwrap_or(0);
                Value::String(format!(
                    "{}#[fg=yellow,bold]{}#[default]{}",
                    &label[..index],
                    &label[index..index + 1],
                    &label[index + 1..]
                ))
            })
            .collect(),
    )
}

fn trim_text(text: &str, max: usize) -> String {
    if text.chars().count() <= max {
        return text.to_owned();
    }
    if max <= 1 {
        return text.chars().take(max).collect();
    }
    format!("{}…", text.chars().take(max - 1).collect::<String>())
}

fn normalize_path(path: Option<&str>, project_root: &str) -> String {
    path.map(str::trim)
        .filter(|value| !value.is_empty())
        .unwrap_or(project_root)
        .to_owned()
}

fn resolve_current_session_id(input: &Value) -> Option<String> {
    let data = input.get("data")?;
    let project_root = string_field(input, "projectRoot").unwrap_or("");
    if let Some(window_id) = string_field(input, "currentWindowId")
        && let Some(id) = all_sessions(data)
            .iter()
            .find(|session| string_field(session, "tmuxWindowId") == Some(window_id))
            .and_then(|session| string_field(session, "id"))
    {
        return Some(id.to_owned());
    }
    if let Some(current_window) =
        string_field(input, "currentWindow").filter(|_| !project_root.is_empty())
    {
        let scoped =
            resolve_scoped_worktree_path(data, project_root, string_field(input, "currentPath"));
        if let Some(id) = sessions_matching(data, "sessions", &scoped, current_window, project_root)
            .first()
            .and_then(|session| string_field(session, "id"))
        {
            return Some(id.to_owned());
        }
        if let Some(id) =
            sessions_matching(data, "teammates", &scoped, current_window, project_root)
                .first()
                .and_then(|session| string_field(session, "id"))
        {
            return Some(id.to_owned());
        }
    }
    data.get("sessions")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .find(|session| bool_field(session, "active"))
        .and_then(|session| string_field(session, "id"))
        .map(ToOwned::to_owned)
}

fn resolve_exact_current_session_id(input: &Value) -> Option<String> {
    let data = input.get("data")?;
    let project_root = string_field(input, "projectRoot").unwrap_or("");
    if let Some(window_id) = string_field(input, "currentWindowId")
        && let Some(id) = all_sessions(data)
            .iter()
            .find(|session| string_field(session, "tmuxWindowId") == Some(window_id))
            .and_then(|session| string_field(session, "id"))
    {
        return Some(id.to_owned());
    }
    if let Some(current_window) =
        string_field(input, "currentWindow").filter(|_| !project_root.is_empty())
    {
        let scoped =
            resolve_scoped_worktree_path(data, project_root, string_field(input, "currentPath"));
        let visible = sessions_matching(data, "sessions", &scoped, current_window, project_root);
        if visible.len() == 1 {
            return string_field(visible[0], "id").map(ToOwned::to_owned);
        }
        if visible.len() > 1 {
            return None;
        }
        let teammates = sessions_matching(data, "teammates", &scoped, current_window, project_root);
        if teammates.len() == 1 {
            return string_field(teammates[0], "id").map(ToOwned::to_owned);
        }
    }
    None
}

fn resolve_scoped_sessions(input: &Value) -> Vec<Value> {
    let Some(data) = input.get("data") else {
        return Vec::new();
    };
    let project_root = string_field(input, "projectRoot").unwrap_or("");
    let scoped =
        resolve_scoped_worktree_path(data, project_root, string_field(input, "currentPath"));
    let mut agents = Vec::new();
    let mut services = Vec::new();
    for session in data
        .get("sessions")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
    {
        if matches!(string_field(session, "status"), Some("offline" | "exited"))
            || is_project_control_session(session)
            || normalize_path(string_field(session, "worktreePath"), project_root) != scoped
        {
            continue;
        }
        if string_field(session, "kind") == Some("service") {
            services.push(session);
        } else {
            agents.push(session);
        }
    }
    agents
        .into_iter()
        .chain(services)
        .take(5)
        .map(|session| resolved_session(data, session, is_current_session(input, session)))
        .collect()
}

fn resolve_focused_control(input: &Value, flag: &str) -> Value {
    let Some(data) = input.get("data") else {
        return Value::Null;
    };
    let Some(current) = resolve_exact_current_session_id(input) else {
        return Value::Null;
    };
    let Some(session) = data
        .get("sessions")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .find(|session| string_field(session, "id") == Some(&current) && bool_field(session, flag))
    else {
        return Value::Null;
    };
    if matches!(string_field(session, "status"), Some("offline" | "exited")) {
        return Value::Null;
    }
    resolved_session(data, session, true)
}

fn resolve_focused_teammate_group(input: &Value) -> Vec<Value> {
    let Some(data) = input.get("data") else {
        return Vec::new();
    };
    let Some(current) = resolve_exact_current_session_id(input) else {
        return Vec::new();
    };
    let Some(parent) = data
        .get("teammates")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .find(|session| string_field(session, "id") == Some(&current))
        .and_then(|session| session.get("team"))
        .and_then(|team| string_field(team, "parentSessionId"))
    else {
        return Vec::new();
    };
    let mut teammates = data
        .get("teammates")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter(|session| {
            session
                .get("team")
                .and_then(|team| string_field(team, "parentSessionId"))
                == Some(parent)
                && !matches!(string_field(session, "status"), Some("offline" | "exited"))
        })
        .collect::<Vec<_>>();
    teammates.sort_by(compare_teammates);
    teammates
        .into_iter()
        .take(5)
        .map(|session| {
            resolved_session(data, session, string_field(session, "id") == Some(&current))
        })
        .collect()
}

fn resolve_current_teammates(input: &Value) -> Vec<Value> {
    let Some(data) = input.get("data") else {
        return Vec::new();
    };
    let Some(parent_id) = resolve_exact_current_session_id(input) else {
        return Vec::new();
    };
    if data
        .get("sessions")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .find(|session| string_field(session, "id") == Some(&parent_id))
        .is_none_or(is_teammate_session)
    {
        return Vec::new();
    }
    let mut teammates = data
        .get("teammates")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter(|session| {
            session
                .get("team")
                .and_then(|team| string_field(team, "parentSessionId"))
                == Some(parent_id.as_str())
                && !matches!(string_field(session, "status"), Some("offline" | "exited"))
        })
        .collect::<Vec<_>>();
    teammates.sort_by(compare_teammates);
    teammates
        .into_iter()
        .take(5)
        .map(|session| resolved_session(data, session, false))
        .collect()
}

fn resolve_session_metadata(input: &Value, exact: bool) -> Value {
    let Some(data) = input.get("data") else {
        return Value::Null;
    };
    let active = if exact {
        resolve_exact_current_session_id(input)
    } else {
        resolve_current_session_id(input)
    };
    active
        .and_then(|id| data.get("metadata").and_then(|metadata| metadata.get(id)))
        .cloned()
        .unwrap_or(Value::Null)
}

fn resolved_session(data: &Value, session: &Value, is_current: bool) -> Value {
    let mut object = session.as_object().cloned().unwrap_or_default();
    if let Some(metadata) = string_field(session, "id")
        .and_then(|id| data.get("metadata").and_then(|metadata| metadata.get(id)))
    {
        if let Some(derived) = metadata.get("derived") {
            object.insert("derived".to_owned(), derived.clone());
        }
        object.insert("metadata".to_owned(), metadata.clone());
    }
    object.insert("isCurrent".to_owned(), Value::Bool(is_current));
    Value::Object(object)
}

fn is_current_session(input: &Value, session: &Value) -> bool {
    if let Some(window_id) = string_field(input, "currentWindowId") {
        string_field(session, "tmuxWindowId") == Some(window_id)
    } else {
        bool_field(session, "active")
    }
}

fn resolve_scoped_worktree_path(
    data: &Value,
    project_root: &str,
    current_path: Option<&str>,
) -> String {
    let current = normalize_path(current_path, project_root);
    let mut candidates = all_sessions(data)
        .into_iter()
        .map(|session| normalize_path(string_field(session, "worktreePath"), project_root))
        .filter(|path| current == *path || current.starts_with(&format!("{path}/")))
        .collect::<Vec<_>>();
    candidates.sort_by_key(|right| std::cmp::Reverse(right.len()));
    candidates.into_iter().next().unwrap_or(current)
}

fn sessions_matching<'a>(
    data: &'a Value,
    key: &str,
    scoped: &str,
    current_window: &str,
    project_root: &str,
) -> Vec<&'a Value> {
    data.get(key)
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .filter(|session| {
            normalize_path(string_field(session, "worktreePath"), project_root) == scoped
                && (string_field(session, "windowName") == Some(current_window)
                    || string_field(session, "label") == Some(current_window)
                    || string_field(session, "tool") == Some(current_window))
        })
        .collect()
}

fn all_sessions(data: &Value) -> Vec<&Value> {
    data.get("sessions")
        .and_then(Value::as_array)
        .into_iter()
        .flatten()
        .chain(
            data.get("teammates")
                .and_then(Value::as_array)
                .into_iter()
                .flatten(),
        )
        .collect()
}

fn is_project_control_session(session: &Value) -> bool {
    bool_field(session, "projectControl")
        || bool_field(session, "overseer")
        || bool_field(session, "scribe")
        || session
            .get("team")
            .and_then(|team| string_field(team, "role"))
            == Some("overseer")
        || session
            .get("team")
            .and_then(|team| string_field(team, "role"))
            == Some("scribe")
}

fn is_teammate_session(session: &Value) -> bool {
    session
        .get("team")
        .and_then(|team| string_field(team, "parentSessionId"))
        .is_some_and(|value| !value.is_empty())
}

fn compare_teammates(left: &&Value, right: &&Value) -> std::cmp::Ordering {
    let left_order = left
        .get("team")
        .and_then(|team| integer_opt(team, "order"))
        .unwrap_or(i64::MAX);
    let right_order = right
        .get("team")
        .and_then(|team| integer_opt(team, "order"))
        .unwrap_or(i64::MAX);
    left_order
        .cmp(&right_order)
        .then_with(|| {
            string_field(left, "createdAt")
                .unwrap_or("")
                .cmp(string_field(right, "createdAt").unwrap_or(""))
        })
        .then_with(|| {
            string_field(left, "id")
                .unwrap_or("")
                .cmp(string_field(right, "id").unwrap_or(""))
        })
}

fn optional_string(value: Option<String>) -> Value {
    value.map(Value::String).unwrap_or(Value::Null)
}

fn string_field<'a>(value: &'a Value, key: &str) -> Option<&'a str> {
    value.get(key).and_then(Value::as_str)
}

fn bool_field(value: &Value, key: &str) -> bool {
    value.get(key).and_then(Value::as_bool).unwrap_or(false)
}

fn integer_field(value: &Value, key: &str) -> i64 {
    integer_opt(value, key).unwrap_or_default()
}

fn integer_opt(value: &Value, key: &str) -> Option<i64> {
    value.get(key).and_then(Value::as_i64)
}
