name = "aimux-relay"
main = "src/index.ts"
account_id = "14238866831e48d4eaf3aab8f6d30272"
compatibility_date = "2025-05-19"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "RELAY", class_name = "RelayObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["RelayObject"]

[env.production]
name = "aimux-relay"
routes = [
  { pattern = "relay.aimux.app", custom_domain = true }
]

[env.production.durable_objects]
bindings = [
  { name = "RELAY", class_name = "RelayObject" }
]
