import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { mkdirSync, mkdtempSync, rmSync, symlinkSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import {
  assertPublishableSource,
  createPathAttachment,
  forgetSessionAttachments,
  listSessionAttachments,
  isSensitiveAttachmentSource,
  createUploadedAttachment,
  getAttachmentContent,
  getAttachmentRecord,
} from "./attachment-store.js";
import { initPaths } from "./paths.js";

describe("attachment-store path attachments", () => {
  let repoRoot = "";

  beforeEach(async () => {
    repoRoot = mkdtempSync(join(tmpdir(), "aimux-attachment-store-"));
    mkdirSync(join(repoRoot, ".git"), { recursive: true });
    await initPaths(repoRoot);
  });

  afterEach(() => {
    rmSync(repoRoot, { recursive: true, force: true });
  });

  it("copies a regular project file into a session-bound attachment", () => {
    const sourcePath = join(repoRoot, "notes.txt");
    writeFileSync(sourcePath, "hello attachment");

    const attachment = createPathAttachment({
      projectRoot: repoRoot,
      sourcePath,
      sessionId: "codex-1",
    });

    expect(attachment).toMatchObject({
      kind: "text",
      filename: "notes.txt",
      mimeType: "text/plain",
      source: "path",
      sessionId: "codex-1",
    });
    const record = getAttachmentRecord(attachment.id, "codex-1");
    expect(record?.contentPath).toContain(join(repoRoot, ".aimux", "attachments"));
    const content = getAttachmentContent(attachment.id, "codex-1");
    expect(content?.buffer.toString("utf8")).toBe("hello attachment");
  });

  it("rejects files outside the project, its worktrees, and temp", () => {
    // Outside every publishable root on macOS and Linux alike.
    expect(() =>
      createPathAttachment({
        projectRoot: repoRoot,
        sourcePath: "/etc/hosts",
        sessionId: "codex-1",
      }),
    ).toThrow("attachment source must be inside the project, one of its worktrees, or a temporary directory");
  });

  it("publishes what an agent wrote to its scratch directory", () => {
    const scratchRoot = mkdtempSync(join(tmpdir(), "aimux-agent-scratch-"));
    const sourcePath = join(scratchRoot, "generated.txt");
    writeFileSync(sourcePath, "generated by the agent");
    try {
      const attachment = createPathAttachment({
        projectRoot: repoRoot,
        sourcePath,
        sessionId: "codex-1",
      });

      expect(attachment).toMatchObject({ filename: "generated.txt", source: "path" });
    } finally {
      rmSync(scratchRoot, { recursive: true, force: true });
    }
  });

  it("refuses credential files even from inside the project", () => {
    for (const name of [".env", "id_rsa", "server.pem", "credentials.json"]) {
      const sourcePath = join(repoRoot, name);
      writeFileSync(sourcePath, "secret");

      expect(() => createPathAttachment({ projectRoot: repoRoot, sourcePath, sessionId: "codex-1" })).toThrow(
        "looks like a credential or secret file",
      );
    }
  });

  it("refuses a credential file reached through an allowed directory", () => {
    const keyDir = join(repoRoot, ".ssh");
    mkdirSync(keyDir, { recursive: true });
    const sourcePath = join(keyDir, "known_hosts");
    writeFileSync(sourcePath, "not really a key, but the directory is off limits");

    expect(() => createPathAttachment({ projectRoot: repoRoot, sourcePath, sessionId: "codex-1" })).toThrow(
      "looks like a credential or secret file",
    );
  });

  it("rejects symlinks that point outside the project", () => {
    const outsideRoot = mkdtempSync(join(tmpdir(), "aimux-attachment-outside-"));
    const outsidePath = join(outsideRoot, "secret.txt");
    const linkPath = join(repoRoot, "secret-link.txt");
    writeFileSync(outsidePath, "nope");
    symlinkSync(outsidePath, linkPath);
    try {
      expect(() =>
        createPathAttachment({
          projectRoot: repoRoot,
          sourcePath: linkPath,
          sessionId: "codex-1",
        }),
      ).toThrow("attachment source must be a regular file");
    } finally {
      rmSync(outsideRoot, { recursive: true, force: true });
    }
  });

  it("stores hosted attachment display metadata on uploaded attachments", () => {
    const attachment = createUploadedAttachment({
      filename: "screen.png",
      mimeType: "image/png",
      dataBase64: Buffer.from("png-bytes").toString("base64"),
      sessionId: "codex-1",
      hostedAttachment: {
        contentUrl: "https://relay.aimux.app/attachments/hosted/ha_1234567890123456789012345678901234567890123/content",
        expiresAt: "2099-01-01T00:00:00.000Z",
        sha256: "ea80334363eed145dfeee51ebae7dc3f1cd7d0c7879f8bfd2070c061d3c33f56",
        sizeBytes: 9,
      },
    });

    expect(attachment).toMatchObject({
      hostedContentUrl:
        "https://relay.aimux.app/attachments/hosted/ha_1234567890123456789012345678901234567890123/content",
      hostedExpiresAt: "2099-01-01T00:00:00.000Z",
    });
    expect(getAttachmentRecord(attachment.id, "codex-1")?.hostedAttachment).toMatchObject({
      contentUrl: attachment.hostedContentUrl,
      expiresAt: attachment.hostedExpiresAt,
    });
  });

  it("stores hosted attachment display metadata on path attachments", () => {
    const sourcePath = join(repoRoot, "screen.png");
    writeFileSync(sourcePath, "png-bytes");

    const attachment = createPathAttachment({
      projectRoot: repoRoot,
      sourcePath,
      sessionId: "codex-1",
      hostedAttachment: {
        contentUrl: "https://relay.aimux.app/attachments/hosted/ha_1234567890123456789012345678901234567890123/content",
        expiresAt: "2099-01-01T00:00:00.000Z",
        sha256: "ea80334363eed145dfeee51ebae7dc3f1cd7d0c7879f8bfd2070c061d3c33f56",
        sizeBytes: 9,
      },
    });

    expect(attachment).toMatchObject({
      hostedContentUrl:
        "https://relay.aimux.app/attachments/hosted/ha_1234567890123456789012345678901234567890123/content",
      hostedExpiresAt: "2099-01-01T00:00:00.000Z",
    });
  });

  it("rejects uploaded hosted metadata that does not match the bytes", () => {
    expect(() =>
      createUploadedAttachment({
        filename: "screen.png",
        mimeType: "image/png",
        dataBase64: Buffer.from("other").toString("base64"),
        sessionId: "codex-1",
        hostedAttachment: {
          contentUrl:
            "https://relay.aimux.app/attachments/hosted/ha_1234567890123456789012345678901234567890123/content",
          expiresAt: "2099-01-01T00:00:00.000Z",
          sha256: "ea80334363eed145dfeee51ebae7dc3f1cd7d0c7879f8bfd2070c061d3c33f56",
          sizeBytes: 9,
        },
      }),
    ).toThrow("hosted attachment checksum mismatch");
  });
});

describe("assertPublishableSource", () => {
  it("returns the resolved path so callers cannot read something else", () => {
    const scratchRoot = mkdtempSync(join(tmpdir(), "aimux-publishable-"));
    const sourcePath = join(scratchRoot, "chart.png");
    writeFileSync(sourcePath, "png");
    try {
      const resolved = assertPublishableSource({ sourcePath, projectRoot: "/nonexistent-project" });

      expect(resolved.endsWith("chart.png")).toBe(true);
    } finally {
      rmSync(scratchRoot, { recursive: true, force: true });
    }
  });

  it("says so plainly when the source is not there", () => {
    expect(() =>
      assertPublishableSource({ sourcePath: "/does/not/exist.png", projectRoot: "/nonexistent-project" }),
    ).toThrow("attachment source does not exist");
  });

  it("refuses a readable file outside every root before any caller reads it", () => {
    expect(() => assertPublishableSource({ sourcePath: "/etc/hosts", projectRoot: "/nonexistent-project" })).toThrow(
      "attachment source must be inside the project",
    );
  });

  it("refuses a credential file that happens to sit in temp", () => {
    const scratchRoot = mkdtempSync(join(tmpdir(), "aimux-publishable-"));
    const sourcePath = join(scratchRoot, "deploy.pem");
    writeFileSync(sourcePath, "-----BEGIN PRIVATE KEY-----");
    try {
      expect(() => assertPublishableSource({ sourcePath, projectRoot: "/nonexistent-project" })).toThrow(
        "looks like a credential or secret file",
      );
    } finally {
      rmSync(scratchRoot, { recursive: true, force: true });
    }
  });
});

describe("isSensitiveAttachmentSource", () => {
  it("matches on path segments and filenames, not substrings", () => {
    expect(isSensitiveAttachmentSource("/Users/sam/.ssh/id_rsa")).toBe(true);
    expect(isSensitiveAttachmentSource("/tmp/scratch/server.PEM")).toBe(true);
    expect(isSensitiveAttachmentSource("/repo/.env.local")).toBe(true);
    expect(isSensitiveAttachmentSource("/repo/app/.envoy.ts")).toBe(false);
    expect(isSensitiveAttachmentSource("/repo/notes.sshx")).toBe(false);
    expect(isSensitiveAttachmentSource("/repo/chart.png")).toBe(false);
    expect(isSensitiveAttachmentSource("/repo/.envrc")).toBe(true);
    expect(isSensitiveAttachmentSource("/repo/.git-credentials")).toBe(true);
    expect(isSensitiveAttachmentSource("/repo/store.keystore")).toBe(true);
  });

  it("still allows committed env templates", () => {
    expect(isSensitiveAttachmentSource("/repo/.env.example")).toBe(false);
    expect(isSensitiveAttachmentSource("/repo/app/.env.sample")).toBe(false);
  });
});

describe("listSessionAttachments", () => {
  let repoRoot = "";

  beforeEach(async () => {
    repoRoot = mkdtempSync(join(tmpdir(), "aimux-recent-attachments-"));
    mkdirSync(join(repoRoot, ".git"), { recursive: true });
    await initPaths(repoRoot);
    forgetSessionAttachments();
  });

  afterEach(() => {
    forgetSessionAttachments();
    rmSync(repoRoot, { recursive: true, force: true });
  });

  it("remembers what a session published, newest first", () => {
    for (const name of ["one.txt", "two.txt"]) {
      const sourcePath = join(repoRoot, name);
      writeFileSync(sourcePath, name);
      createPathAttachment({ projectRoot: repoRoot, sourcePath, sessionId: "codex-1" });
    }

    const recent = listSessionAttachments("codex-1");

    expect(recent.map((entry) => entry.record.filename)).toEqual(["two.txt", "one.txt"]);
  });

  it("keeps one session's publishes out of another's", () => {
    const sourcePath = join(repoRoot, "mine.txt");
    writeFileSync(sourcePath, "mine");
    createPathAttachment({ projectRoot: repoRoot, sourcePath, sessionId: "codex-1" });

    expect(listSessionAttachments("claude-2")).toEqual([]);
  });

  it("ignores what the operator uploaded from the composer", () => {
    createUploadedAttachment({
      filename: "screenshot.png",
      mimeType: "image/png",
      dataBase64: Buffer.from("png-bytes").toString("base64"),
      sessionId: "codex-1",
    });

    expect(listSessionAttachments("codex-1")).toEqual([]);
  });
});

describe("session attachment hydration", () => {
  let repoRoot = "";

  beforeEach(async () => {
    repoRoot = mkdtempSync(join(tmpdir(), "aimux-hydrate-attachments-"));
    mkdirSync(join(repoRoot, ".git"), { recursive: true });
    await initPaths(repoRoot);
    forgetSessionAttachments();
  });

  afterEach(() => {
    forgetSessionAttachments();
    rmSync(repoRoot, { recursive: true, force: true });
  });

  it("finds publishes written before this process started", () => {
    const sourcePath = join(repoRoot, "earlier.txt");
    writeFileSync(sourcePath, "earlier");
    createPathAttachment({ projectRoot: repoRoot, sourcePath, sessionId: "codex-1" });

    // As if the service had restarted: the records are on disk, the map is not.
    forgetSessionAttachments();

    expect(listSessionAttachments("codex-1").map((entry) => entry.record.filename)).toEqual(["earlier.txt"]);
  });
});
