import { basename } from "node:path";
import type { AgentActivityState, AgentAttentionState } from "./agent-events.js";
import type { SessionSemanticState } from "./session-semantics.js";
import { sessionSemanticCompactHint } from "./session-semantics.js";
import type { SessionTeamMetadata } from "./team.js";
import { compareTeammateSessions, isTeammateSession } from "./team.js";

export interface StatuslineSession {
  id: string;
  kind?: "agent" | "service";
  tool: string;
  label?: string;
  launchCommandLine?: string;
  tmuxWindowId?: string;
  tmuxWindowIndex?: number;
  windowName?: string;
  headline?: string;
  status?: string;
  role?: string;
  active?: boolean;
  worktreePath?: string;
  semantic?: SessionSemanticState;
  team?: SessionTeamMetadata;
}

function isAutogeneratedSessionLabel(session: Pick<StatuslineSession, "tool" | "label">): boolean {
  const label = session.label?.trim().toLowerCase();
  const tool = session.tool?.trim().toLowerCase();
  if (!label || !tool) return false;
  return label === tool || label.startsWith(`${tool}-`);
}

export function compactSessionTitle(
  session: Pick<StatuslineSession, "kind" | "tool" | "label" | "launchCommandLine" | "role" | "id">,
): string {
  if (session.kind === "service") {
    const command = session.launchCommandLine?.trim();
    if (command) return command;
  }
  const base =
    session.kind === "service"
      ? session.label?.trim() || session.tool || "service"
      : !isAutogeneratedSessionLabel(session) && session.label?.trim()
        ? session.label.trim()
        : session.tool || session.id;
  if (session.kind === "service") {
    return `${base}[svc]`;
  }
  return session.role ? `${base}(${session.role})` : base;
}

export interface StatuslineMetadataEntry {
  status?: { text: string; tone?: string };
  progress?: { current: number; total: number; label?: string };
  logs?: Array<{ message: string; source?: string; tone?: string; ts: string }>;
  statusline?: {
    top?: Array<{ id?: string; text: string; tone?: string }>;
    bottom?: Array<{ id?: string; text: string; tone?: string }>;
  };
  context?: {
    cwd?: string;
    worktreePath?: string;
    worktreeName?: string;
    branch?: string;
    pr?: { number?: number; title?: string; url?: string; headRef?: string; baseRef?: string };
    repo?: { owner?: string; name?: string; remote?: string };
  };
  derived?: {
    activity?: AgentActivityState;
    attention?: AgentAttentionState;
    unseenCount?: number;
    services?: Array<{ label?: string; url?: string; port?: number }>;
  };
  updatedAt?: string;
}

export interface StatuslineData {
  project?: string;
  dashboardScreen?: "dashboard" | "graveyard" | "coordination" | "project" | "library" | "topology" | "help";
  sessions?: StatuslineSession[];
  teammates?: StatuslineSession[];
  metadata?: Record<string, StatuslineMetadataEntry>;
  controlPlane?: {
    daemonAlive?: boolean;
    projectServiceAlive?: boolean;
  };
  tasks?: {
    pending?: number;
    assigned?: number;
  };
  flash?: string | null;
  updatedAt?: string;
}

export interface ResolvedStatuslineSession extends StatuslineSession {
  derived?: StatuslineMetadataEntry["derived"];
  metadata?: StatuslineMetadataEntry;
  isCurrent: boolean;
}

export const DASHBOARD_SCREEN_TABS: Array<{
  key: NonNullable<StatuslineData["dashboardScreen"]>;
  label: string;
  hotkey: string;
}> = [
  { key: "dashboard", label: "dashboard", hotkey: "d" },
  { key: "coordination", label: "coordination", hotkey: "c" },
  { key: "project", label: "project", hotkey: "p" },
  { key: "library", label: "library", hotkey: "l" },
  { key: "topology", label: "topology", hotkey: "t" },
  { key: "graveyard", label: "graveyard", hotkey: "g" },
];

export function trim(text: string, max: number): string {
  if (text.length <= max) return text;
  if (max <= 1) return text.slice(0, max);
  return `${text.slice(0, Math.max(0, max - 1))}…`;
}

export function normalizePath(path: string | undefined, projectRoot: string): string {
  return path?.trim() || projectRoot;
}

function isWithinPath(path: string, root: string): boolean {
  return path === root || path.startsWith(`${root}/`);
}

function resolveScopedWorktreePath(data: StatuslineData, projectRoot: string, currentPath?: string): string {
  const normalizedCurrentPath = normalizePath(currentPath, projectRoot);
  const candidates = [...(data.sessions ?? []), ...(data.teammates ?? [])]
    .map((session) => normalizePath(session.worktreePath, projectRoot))
    .filter((worktreePath) => isWithinPath(normalizedCurrentPath, worktreePath))
    .sort((left, right) => right.length - left.length);
  return candidates[0] ?? normalizedCurrentPath;
}

function allStatuslineSessions(data: StatuslineData): StatuslineSession[] {
  return [...(data.sessions ?? []), ...(data.teammates ?? [])];
}

export function findStatuslineSession(
  data: StatuslineData,
  sessionId: string | undefined,
): StatuslineSession | undefined {
  if (!sessionId) return undefined;
  return allStatuslineSessions(data).find((session) => session.id === sessionId);
}

function sessionsMatchingScopedWindow(
  sessions: StatuslineSession[],
  scopedWorktreePath: string,
  currentWindow: string,
  projectRoot: string,
): StatuslineSession[] {
  return sessions.filter((session) => {
    if (normalizePath(session.worktreePath, projectRoot) !== scopedWorktreePath) return false;
    return session.windowName === currentWindow || session.label === currentWindow || session.tool === currentWindow;
  });
}

export function sessionIdentity(
  session: Pick<StatuslineSession, "id" | "tool" | "label" | "launchCommandLine" | "role">,
): string {
  return compactSessionTitle(session);
}

export function renderSemanticBadge(semantic: SessionSemanticState | undefined): string | null {
  if (!semantic) return null;
  if (semantic.user.attention === "error") return "✗";
  if (semantic.user.attention === "needs_input") return "?";
  if (semantic.user.attention === "needs_response") return "?";
  if (semantic.user.attention === "blocked") return "!";
  if (semantic.user.label === "done") return "✓";
  if (semantic.user.label === "working") return "↻";
  if (semantic.user.label === "starting") return "…";
  return null;
}

export function renderSessionCompactHint(session: {
  semantic?: SessionSemanticState;
  derived?: StatuslineMetadataEntry["derived"];
}): string | null {
  if (session.semantic) {
    return sessionSemanticCompactHint(session.semantic);
  }
  return null;
}

export function renderDashboardScreens(activeScreen: StatuslineData["dashboardScreen"]): string[] {
  const active = activeScreen ?? "dashboard";
  return DASHBOARD_SCREEN_TABS.map((screen) => {
    if (screen.key === active) {
      return `#[fg=black,bg=yellow] ${screen.label} #[default]`;
    }
    // Accent the leading letter to signal the screen's hotkey.
    const [first, ...rest] = screen.label;
    return `#[fg=yellow,bold]${first}#[default]${rest.join("")}`;
  });
}

export function currentPathContext(currentPath: string | undefined): { worktreeName?: string; branch?: string } | null {
  if (!currentPath) return null;
  const worktreeName = basename(currentPath);
  return {
    worktreeName: worktreeName || undefined,
  };
}

export function resolveCurrentSessionId(
  data: StatuslineData,
  currentSession?: string,
  currentWindow?: string,
  currentWindowId?: string,
  currentPath?: string,
  projectRoot?: string,
): string | undefined {
  const sessions = allStatuslineSessions(data);
  if (currentWindowId) {
    const byWindow = sessions.find((session) => session.tmuxWindowId === currentWindowId);
    if (byWindow?.id) return byWindow.id;
  }
  if (currentWindow && projectRoot) {
    const scopedWorktreePath = resolveScopedWorktreePath(data, projectRoot, currentPath);
    const visibleMatch = sessionsMatchingScopedWindow(
      data.sessions ?? [],
      scopedWorktreePath,
      currentWindow,
      projectRoot,
    )[0];
    if (visibleMatch?.id) return visibleMatch.id;
    const teammateMatch = sessionsMatchingScopedWindow(
      data.teammates ?? [],
      scopedWorktreePath,
      currentWindow,
      projectRoot,
    )[0];
    if (teammateMatch?.id) return teammateMatch.id;
  }
  return data.sessions?.find((session) => session.active)?.id;
}

export function resolveExactCurrentSessionId(
  data: StatuslineData,
  currentSession?: string,
  currentWindow?: string,
  currentWindowId?: string,
  currentPath?: string,
  projectRoot?: string,
): string | undefined {
  const sessions = allStatuslineSessions(data);
  if (currentWindowId) {
    const byWindow = sessions.find((session) => session.tmuxWindowId === currentWindowId);
    if (byWindow?.id) return byWindow.id;
  }
  if (currentWindow && projectRoot) {
    const scopedWorktreePath = resolveScopedWorktreePath(data, projectRoot, currentPath);
    const visibleMatches = sessionsMatchingScopedWindow(
      data.sessions ?? [],
      scopedWorktreePath,
      currentWindow,
      projectRoot,
    );
    if (visibleMatches.length === 1) {
      return visibleMatches[0]?.id;
    }
    if (visibleMatches.length > 1) {
      return undefined;
    }
    const teammateMatches = sessionsMatchingScopedWindow(
      data.teammates ?? [],
      scopedWorktreePath,
      currentWindow,
      projectRoot,
    );
    if (teammateMatches.length === 1) {
      return teammateMatches[0]?.id;
    }
  }
  return undefined;
}

export function resolveScopedSessions(
  data: StatuslineData,
  projectRoot: string,
  currentSession?: string,
  currentWindow?: string,
  currentWindowId?: string,
  currentPath?: string,
): ResolvedStatuslineSession[] {
  const scopedWorktreePath = resolveScopedWorktreePath(data, projectRoot, currentPath);
  const scopedSessions = (data.sessions ?? [])
    .filter((session) => session.status !== "offline" && session.status !== "exited")
    .filter((session) => normalizePath(session.worktreePath, projectRoot) === scopedWorktreePath);
  return [
    ...scopedSessions.filter((session) => session.kind !== "service"),
    ...scopedSessions.filter((session) => session.kind === "service"),
  ]
    .slice(0, 5)
    .map((session) => {
      const resolvedMetadata = data.metadata?.[session.id];
      return {
        ...session,
        derived: resolvedMetadata?.derived,
        semantic: session.semantic,
        metadata: resolvedMetadata,
        isCurrent: currentWindowId ? session.tmuxWindowId === currentWindowId : Boolean(session.active),
      };
    });
}

export function resolveFocusedTeammate(
  data: StatuslineData,
  projectRoot: string,
  currentSession?: string,
  currentWindow?: string,
  currentWindowId?: string,
  currentPath?: string,
): ResolvedStatuslineSession | null {
  const exactCurrentSessionId = resolveExactCurrentSessionId(
    data,
    currentSession,
    currentWindow,
    currentWindowId,
    currentPath,
    projectRoot,
  );
  if (!exactCurrentSessionId) return null;
  const teammate = (data.teammates ?? []).find((session) => session.id === exactCurrentSessionId);
  if (!teammate || teammate.status === "offline" || teammate.status === "exited") return null;
  const resolvedMetadata = data.metadata?.[teammate.id];
  return {
    ...teammate,
    derived: resolvedMetadata?.derived,
    semantic: teammate.semantic,
    metadata: resolvedMetadata,
    isCurrent: true,
  };
}

export function resolveFocusedTeammateGroup(
  data: StatuslineData,
  projectRoot: string,
  currentSession?: string,
  currentWindow?: string,
  currentWindowId?: string,
  currentPath?: string,
): ResolvedStatuslineSession[] {
  const focusedTeammate = resolveFocusedTeammate(
    data,
    projectRoot,
    currentSession,
    currentWindow,
    currentWindowId,
    currentPath,
  );
  const parentSessionId = focusedTeammate?.team?.parentSessionId;
  if (!focusedTeammate || !parentSessionId) return [];
  return (data.teammates ?? [])
    .filter((session) => session.team?.parentSessionId === parentSessionId)
    .filter((session) => session.status !== "offline" && session.status !== "exited")
    .sort(compareTeammateSessions)
    .slice(0, 5)
    .map((session) => {
      const resolvedMetadata = data.metadata?.[session.id];
      return {
        ...session,
        derived: resolvedMetadata?.derived,
        semantic: session.semantic,
        metadata: resolvedMetadata,
        isCurrent: session.id === focusedTeammate.id,
      };
    });
}

export function resolveCurrentTeammates(
  data: StatuslineData,
  projectRoot: string,
  currentSession?: string,
  currentWindow?: string,
  currentWindowId?: string,
  currentPath?: string,
): ResolvedStatuslineSession[] {
  const parentSessionId = resolveExactCurrentSessionId(
    data,
    currentSession,
    currentWindow,
    currentWindowId,
    currentPath,
    projectRoot,
  );
  if (!parentSessionId) return [];
  const parentSession = (data.sessions ?? []).find((session) => session.id === parentSessionId);
  if (!parentSession || isTeammateSession(parentSession)) return [];
  return (data.teammates ?? [])
    .filter((session) => session.team?.parentSessionId === parentSessionId)
    .filter((session) => session.status !== "offline" && session.status !== "exited")
    .sort(compareTeammateSessions)
    .slice(0, 5)
    .map((session) => {
      const resolvedMetadata = data.metadata?.[session.id];
      return {
        ...session,
        derived: resolvedMetadata?.derived,
        semantic: session.semantic,
        metadata: resolvedMetadata,
        isCurrent: false,
      };
    });
}

export function resolveSessionMetadata(
  data: StatuslineData,
  projectRoot: string,
  currentSession?: string,
  currentWindow?: string,
  currentWindowId?: string,
  currentPath?: string,
): StatuslineMetadataEntry | undefined {
  const activeSessionId = resolveCurrentSessionId(
    data,
    currentSession,
    currentWindow,
    currentWindowId,
    currentPath,
    projectRoot,
  );
  if (!activeSessionId) return undefined;
  return data.metadata?.[activeSessionId];
}

export function resolveExactSessionMetadata(
  data: StatuslineData,
  projectRoot: string,
  currentSession?: string,
  currentWindow?: string,
  currentWindowId?: string,
  currentPath?: string,
): StatuslineMetadataEntry | undefined {
  const activeSessionId = resolveExactCurrentSessionId(
    data,
    currentSession,
    currentWindow,
    currentWindowId,
    currentPath,
    projectRoot,
  );
  if (!activeSessionId) return undefined;
  return data.metadata?.[activeSessionId];
}
